export const DATABASE_ID = process.env.NEXT_PUBLIC_APPWRITE_DB_ID!;
export const WORKSPACES_ID =
  process.env.NEXT_PUBLIC_APPWRITE_DOCUMENT_WORKSPACES_ID!;
export const STORAGE_BUCKET_ID =
  process.env.NEXT_PUBLIC_APPWRITE_STORAGE_BUCKET_ID!;
export const MEMBERS_ID = process.env.NEXT_PUBLIC_APPWRITE_DOCUMENT_MEMBERS_ID!;
export const PROJECTS_ID =
  process.env.NEXT_PUBLIC_APPWRITE_DOCUMENT_PROJECTS_ID!;
export const TASKS_ID = process.env.NEXT_PUBLIC_APPWRITE_DOCUMENT_TASK_ID!;
